version: '2.1'
services:
  nginx:
    image: nginx:latest
    container_name: lnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - www
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/socket:/var/run"
      - "./nginx/conf.d/:/etc/nginx/conf.d"
      - "/etc/hosts:/etc/hosts"
    links:
      - php-fpm:php-fpm
    networks:
      web_server_network :
        ipv4_address: ${NGINX_WEB_SERVER_IP}

  php-fpm:
    image: a1877361302/php7.4:v10.12
    container_name: lnmp-php-fpm
    ports:
      - "9010:9000"
    volumes_from:
      - www
    volumes:
      - "./nginx/logs/php-fpm:/usr/local/var/log/php7"
      - "./nginx/socket:/var/run"
      - "/etc/hosts:/etc/hosts"
    extra_hosts:
      - "${PHP_FPM_DOMAIN}:${NGINX_WEB_SERVER_IP}"
      - "${PHP_FPM_DOMAIN2}:${NGINX_WEB_SERVER_IP}"
    env_file:
      - .env
    networks:
      - web_server_network

  mysql_7:
    image: mysql:5.7.28
    container_name: lnmp-mysql_7
    ports:
      - "3307:3306"
    volumes:
      - "./mariadb/data/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - web_server_network

  redis:
    build: ./redis
    container_name: lnmp-redis
    # ports:
    #   - "6379:6379"
    volumes:
      - "./redis/data:/data"
    environment:
      - REDIS_PASSWORD=developer
    networks:
      - web_server_network

  ### Web-Root Container #######################################
  www:
    image: tianon/true
    container_name: lnmp-www
    volumes:
      - ./www:/usr/share/nginx/html

### Networks Setup ############################################
networks:
  web_server_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "${WEB_SERVER_SUBNET}"
        gateway: "${WEB_SERVER_GATEWAY}"
